locator_colour = "#colour-picker"
locator_submit = "//*[@id='HTMLFormElements']/div[7]/input[2]"
locator_email = "#email-field"
locator_number = "#number-field"
locator_date = "#date-picker"
locator_date_time = "#date-time-picker"
locator_month = "//*[@id='month-field']"
locator_colour2 = "#_valuecolour"
